/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <canvas.h>
/* Header for class com_example_caffemacchiato_GameLibJNIWrapper */

#ifndef _Included_com_example_caffemacchiato_GameLibJNIWrapper
#define _Included_com_example_caffemacchiato_GameLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_caffemacchiato_GameLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_caffemacchiato_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv * asmd, jclass  asd1){
	on_surface_created();
}

/*
 * Class:     com_example_caffemacchiato_GameLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_caffemacchiato_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv * par, jclass par1, jint par2, jint par3){
	on_surface_changed();
}

/*
 * Class:     com_example_caffemacchiato_GameLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_caffemacchiato_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv * par1, jclass par2){
	on_draw_frame();
}

#ifdef __cplusplus
}
#endif
#endif
